name: geospatial_mlops_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - mlflow
  - airflow
  - scikit-learn
  - sktime
  - statsmodels
  - scipy
  - numpy
  - pandas
  - pyarrow
  - geopandas
  - dask
  - rasterio
  - shapely
  - odc-stac
  - pystac-client
  - openeo
  - matplotlib
  - plotly
  - seaborn
  - pytest
  - python-duckdb
